name: Build VM Disk Image

env:
  PACKER_VERSION: '1.8.4'

on:
  push:
    branches: '*'
    tags: 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
        matrix:
          version:
            - 9.2

          architecture:
            - name: x86-64
              qemu: x86

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependecies
        run: sudo apt update && sudo apt install curl unzip "qemu-system-${{ matrix.architecture.name }}" -y

      - name: Install Packer
        run: |
          curl -o packer.zip -L https://releases.hashicorp.com/packer/${{ env.PACKER_VERSION }}/packer_${{ env.PACKER_VERSION }}_linux_amd64.zip
          unzip packer.zip
          mv packer /usr/local/bin

      - name: Download QEMU UEFI
        if: matrix.architecture.name == 'arm64'
        run: curl -o resources/qemu_efi.fd -L http://releases.linaro.org/components/kernel/uefi-linaro/latest/release/qemu64/QEMU_EFI.fd

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Build Image
        run: |
          PACKER_LOG=1 ./build.sh \
            '${{ matrix.version }}' \
            '${{ matrix.architecture.name }}' \
            -var 'headless=true'

      - name: Extract Version
        id: version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: NetBSD ${{ steps.version.outputs.VERSION }}
          draft: true
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
